#!/bin/bash
set -e

# Create test database and test user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $TEST_POSTGRES_USER WITH PASSWORD '$TEST_POSTGRES_PASSWORD';
    CREATE DATABASE $TEST_POSTGRES_DB;
    GRANT ALL PRIVILEGES ON DATABASE $TEST_POSTGRES_DB TO $TEST_POSTGRES_USER;
EOSQL